name: lc-geo

services:
  agent:
    image: luiskolb/geo-agent:latest
    ports:
      - 8001:8001
    depends_on:
      chromadb:
        condition: service_healthy
  
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - 8000:8000
    volumes:
      - db-data:/chroma/chroma
    healthcheck:
      test: python -c "import requests;requests.get('http://localhost:8000')"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s

volumes:
  db-data:
